language: python

python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6

env:
  - DJANGOVER=django111
  - DJANGOVER=django20

install:
  - pip install tox

script:
  - export TOX_ENV=py${TRAVIS_PYTHON_VERSION/./}-${DJANGOVER}-linux
  - tox -r -e "$TOX_ENV"