language: python

python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6

env:
  - DJANGOVER=django18
  - DJANGOVER=django19
  - DJANGOVER=django110
  - DJANGOVER=django111

install:
  - pip install tox

script:
  - export TOX_ENV=py${TRAVIS_PYTHON_VERSION/./}-${DJANGOVER}-linux
  - tox -r -e "$TOX_ENV"